"""add unique constraint to username

Revision ID: 9770b6ef22fd
Revises: f59c55abca95
Create Date: 2026-04-27 16:58:08.313755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9770b6ef22fd'
down_revision = 'f59c55abca95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_email', ['email'])
        batch_op.create_unique_constraint('unique_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_username', type_='unique')
        batch_op.drop_constraint('unique_email', type_='unique')

    # ### end Alembic commands ###
